language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm-nightly

before_script:
  - composer self-update
  - composer require satooshi/php-coveralls:~1.0 --no-update --dev
  - composer install --dev --prefer-source

after_script:
  - php vendor/bin/coveralls
